### ISSUE TITLE
Windows Installer — Default Path

### ISSUE THREAD

**Issue by fdesbiens** [eclipse-theia/theia-blueprint#89] opened 2021-04-30 13:02 UTC
Hi.

The default installation path in the Theia Blueprint installer is `C:\Program Files\Rob Moran\TheiaBlueprint`. This seems  a bit too specific. 

![TheiaWindowsInstaller](https://user-images.githubusercontent.com/5367020/116698596-8d8bc980-a992-11eb-97cd-f48377967742.png)

I suggest the default to be `C:\Program Files\TheiaBlueprint`. 

Keep up the good work!

**Comment by vince-fugnitto** [comment] 2021-04-30 13:07
@fdesbiens thank you for the report, it is a duplicate of https://github.com/eclipse-theia/theia-blueprint/issues/35.

**Closed by vince-fugnitto** 2021-04-30 13:07 UTC
Labels: duplicate, os: windows

**Comment by fdesbiens** [comment] 2021-04-30 13:09
@vince-fugnitto I checked open issues and somehow missed it. Thank you for the quick reply!
