### ISSUE TITLE
git panel function can't work

### ISSUE THREAD

**Issue by marol1210** [eclipse-theia/theia-blueprint#232] opened 2022-09-14 03:00 UTC
### Bug Description:

just click button `more action`  in git source panel , and  show error  `'git.tags' is not a menu group` in devTools console.

![image](https://user-images.githubusercontent.com/7519301/190048178-5bbd3905-c02c-4d51-b28c-2fb844e0b1a7.png)

### Steps to Reproduce:

1.  just click button `more action`  in git source panel , and  show error  `'git.tags' is not a menu group` in devTools console.
2.
3.

### Additional Information

- Operating System:    windows
- Theia Version:
Version 1.29.0 (Beta)
VS Code API Version: 1.53.2

**Comment by jfaltermeier** [comment] 2022-09-14 08:37
Thank you for the report. I can reproduce the issue. 
We will have a look.

**Comment by marcdumais-work** [comment] 2022-11-04 15:08
It looks like this issue was fixed in the update to [Theia 1.30.0](https://github.com/eclipse-theia/theia-blueprint/pull/234). Please re-open if necessary.

**Closed by marcdumais-work** 2022-11-04 15:08 UTC
