### ISSUE TITLE
AsciiDoc extension does not show images in preview

### ISSUE THREAD

**Issue by vincenzocaselli** [eclipse-theia/theia-blueprint#244] opened 2022-12-03 09:15 UTC
Hi,
I am trying to use the following VS extension
**AsciiDoc**
asciidoctor.asciidoctor-vscode
on **Theia Blueprint 1.32.0 (Beta)** - VS Code API Version: 1.55.2

I am already using this extension on VsCode, so I decided to try it on Theia.
The extension is searchable and installable from the Extensions view and the installation ends successfully.
However, when previewing an asciidoc file with
![image](https://user-images.githubusercontent.com/3648713/205433217-3cda00a8-a9db-46ce-83ef-6e600ed4b3d3.png)

then images are not shown
![image](https://user-images.githubusercontent.com/3648713/205433090-fcbd7716-cbfd-48dd-8ff0-99cc2604a5a0.png)
 (unlike VsCode, where they are visible)

**Steps to Reproduce:**
1. in Theia Blueprint, go to Extension view, type **asciidoc** in search
2. click install on AsciiDoc extension 
![image](https://user-images.githubusercontent.com/3648713/205432995-904d8b93-c331-46b7-b439-6c91a14f948b.png)
3. open an asciidoc file with an image 
or create a brand new one, like the following (name it anyway, but with .adoc extension)
```
:imagesdir: ./img

== Chapter 1
here is the image

image::image1.png[]

``` 
(ensure to have an image named image1.png in a subfolder named img with respect of the .adoc file)

- Operating System: Windows 10
- Theia Version:  Theia Blueprint 1.32.0 (Beta) - VS Code API Version: 1.55.2

Any hints?
Thank you very much
Vincenzo

**Comment by jfaltermeier** [comment] 2022-12-05 13:30
Thanks for the report. Root cause seems to be
```
Refused to load the image 'http://fdd8cdf0-ce21-443a-b44f-e101721b1a49.webview.localhost:34741/webview…/project/files/img/image1.png' because it violates the following Content Security Policy directive: "img-src vscode-resource: https: data:".
```

**Comment by marcdumais-work** [comment] 2022-12-05 17:59
In the upper-right corner of the preview window, there are tree dots "...", under which there are options. Click "change preview security settings". I was only able to make it work with local images using the third option. Ideally the second option would work, limiting the "trust" to local content. I also noted that "refresh preview" does not seem to work - I needed to close the preview and re-open it.

![image](https://user-images.githubusercontent.com/25749063/205703410-1cc34519-7e27-452f-8115-a4d3b55d93e3.png)
![image](https://user-images.githubusercontent.com/25749063/205703648-c34b6ab7-d8f6-4208-8c1c-1c2e9dd2007b.png)
![image](https://user-images.githubusercontent.com/25749063/205703953-50fb9281-471c-46d4-827f-4604ca0dc686.png)

**Comment by vincenzocaselli** [comment] 2022-12-06 21:39
Wow, it works! Great!

A question though: 
since the extension is the same and the behavior is different between **VsCode** and **Theia**, so what is causing **Theia** to need this security change while **VsCode** works out-of-the-box ?

**Comment by marcdumais-work** [comment] 2022-12-12 14:50
> A question though: since the extension is the same and the behavior is different between **VsCode** and **Theia**, so what is causing **Theia** to need this security change while **VsCode** works out-of-the-box ?

Good question - after some investigation, I think it's due to a bug in generic Theia's WebView code, used to display the preview window. I will open an upstream issue when I conclude my investigation - I'm optimistic we can have a fix for this, relatively quick.

**Comment by marcdumais-work** [comment] 2023-01-16 16:32
A [fix for this](https://github.com/eclipse-theia/theia/pull/12070) has been merged upstream and will be part of this month's Eclipse Theia release. We usually update blueprint shortly after a Theia release.

**Comment by vince-fugnitto** [comment] 2023-03-31 17:16
> A [fix for this](https://github.com/eclipse-theia/theia/pull/12070) has been merged upstream and will be part of this month's Eclipse Theia release. We usually update blueprint shortly after a Theia release.

As mentioned, the issue should be fixed in newer versions of Eclipse Theia Blueprint.

**Closed by vince-fugnitto** 2023-03-31 17:16 UTC
