### ISSUE TITLE
Package Size Review

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#39] opened 2021-02-08 14:17 UTC
On macOS, the package (.pkg) installer seems quite large - ~255MB and the space it takes on disk when installed is close to 700MB.

Can/Should it be slimmed down?

**Comment by koegel** [comment] 2021-02-08 21:43
The Windows installer (200 MB) and the Linux package (183 MB) are not significantly smaller. Also when I compare this to an Eclipse IDE package this does not strike me as unexpected.

**Comment by marcdumais-work** [comment] 2021-02-08 21:54
Can someone confirm whether the app is built in production mode, when packaged? 
It does not look like it's the case by default, though it's easy to do it in the CI environment with an extra `yarn build --production`:
https://github.com/eclipse-theia/theia-blueprint/blob/master/electron-app/package.json#L83

If not this could save a bit of space, removing `dev-dependencies` and optionally the `map` and TypeScript source files (at the potential expense of debuggability). 

See this example:
https://github.com/theia-ide/theia-apps/blob/master/theia-go-docker/Dockerfile#L11-L20

**Comment by koegel** [comment] 2021-02-12 00:36
@jfaltermeier Can you please take a look?

**Comment by jfaltermeier** [comment] 2021-02-22 14:24
I tried to build it in production mode, but it did not make a difference regarding the size. However I am not 100% sure I've tried the right things. 
Can we identify whether a production build was done when inspection the unpacked image?

One thing that might be improved is that the electron binaries are available twice. Once in the root and once via: electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron/dist

The electron binaries are between 150 and 200MB. 
The vs code extension also have 150+ MB

**Comment by marcdumais-work** [comment] 2021-03-11 19:44
> Can we identify whether a production build was done when inspection the unpacked image?

One way is to look in `node-modules` for the presence of packages that are purely a `dev-dependency`. In a production build, these would be stripped. Just looking at the number of entries in there could be enough to be pretty sure. If it's 1000+ it's probably not a production build. If it's ~400-500 it's probably a production build.

> One thing that might be improved is that the electron binaries are available twice. Once in the root and once via: electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron/dist

Interesting. On which operating system(s)? I tried to find a link to download a theia-blueprint app package but did not find one. Could you help? I can confirm if it's a production build and if I also see two copies of the Electron binaries.

**Comment by marcdumais-work** [comment] 2021-03-11 20:16
I cloned this repo for the first time and had a quick look. I used the preview packaging mode, that leaves on the file system an unpacked version of the eventual package. 

I confirm that the content of `node_modules` is production-only, so nothing to improve from that aspect:
```bash
/electron-app/dist/linux-unpacked$ ls -al ./resources/app/node_modules/ | wc -l
484
```

Indeed I find two copied of several Electron binaries. It looks-like the Electron `dist` folder was used as the base to create the root content - it's all there in the root with the `electron` binary renamed to `theia-blueprint`. 
```bash
$> yarn && yarn package:preview
$> cd electron-app/dist/linux-unpacked/
$> find . -name libvulkan.so
./resources/app/node_modules/@theia/electron/node_modules/electron/dist/libvulkan.so
./libvulkan.so
```
For a quick test I removed folder `resources/app/node_modules/@theia/electron/node_modules/electron/dist/` and started `blueprint`using the executable at the root. it started/worked well. So maybe we can remove that folder before packaging?

**Comment by marcdumais-work** [comment] 2021-03-11 20:18
Maybe `@theia/electron` needs to be a `dev-dependency`?

**Comment by marcdumais-work** [comment] 2021-03-11 20:35
> The vs code extension also have 150+ MB

Correct and a big chunk of that is in a few extensions, used for advanced development support for HTML and JavaScript/TypeScript. We can eventually have a few extension packs, to install related vscode-builtins. We could have HTML/TS support part of an optional user-installed pack, to save download size.

**Comment by marcdumais-work** [comment] 2021-03-11 20:54
> Maybe `@theia/electron` needs to be a `dev-dependency`?

I have a PR: https://github.com/eclipse-theia/theia-blueprint/pull/49. On Linux this will reduce the unpacked package size by 16MB.

**Comment by brianking** [comment] 2021-03-11 21:00
Excellent investigative work @marcdumais-work , thanks!

**Comment by marcdumais-work** [comment] 2021-03-11 21:03
> > The vs code extension also have 150+ MB
> 
> Correct and a big chunk of that is in a few extensions, used for advanced development support for HTML and JavaScript/TypeScript. We can eventually have a few extension packs, to install related vscode-builtins. We could have HTML/TS support part of an optional user-installed pack, to save download size.

```bash
 theia-blueprint/electron-app/plugins$ du -hs *
48K	alphabotsec.vscode-eclipse-keybindings
3.4M	ms-vscode.js-debug
45M	redhat.java
3.0M	vscjava.vscode-java-debug
1.1M	vscjava.vscode-java-dependency
3.6M	vscjava.vscode-java-test
12M	vscjava.vscode-maven
364K	vscode-builtin-node-debug
3.5M	vscode-builtin-node-debug2
96K	vscode.css
4.2M	vscode.css-language-features
44K	vscode.docker
112K	vscode.html
36M	vscode.html-language-features
136K	vscode.image-preview
48K	vscode.ini
400K	vscode.javascript
52K	vscode.json
3.2M	vscode.json-language-features
40K	vscode.log
100K	vscode.markdown
1.6M	vscode.npm
72K	vscode.powershell
60K	vscode.shellscript
400K	vscode.typescript
32M	vscode.typescript-language-features
56K	vscode.xml
60K	vscode.yaml
```

Here are the biggest extensions we bundle currently (unpacked size). They broadly intend to support Java and JavaScript/TypeScript/HTML development: 
3.4M	ms-vscode.js-debug
45M	redhat.java
3.0M	vscjava.vscode-java-debug
1.1M	vscjava.vscode-java-dependency
3.6M	vscjava.vscode-java-test
12M	vscjava.vscode-maven
364K	vscode-builtin-node-debug
3.5M	vscode-builtin-node-debug2
4.2M	vscode.css-language-features
36M	vscode.html-language-features
3.2M	vscode.json-language-features
1.6M	vscode.npm
32M	vscode.typescript-language-features

Regarding the idea of making vscode-builtins available in various complementary extension packs, see: https://github.com/eclipse-theia/vscode-builtin-extensions/issues/40#issuecomment-766996063

**Comment by marcdumais-work** [comment] 2021-03-12 16:55
We ended-up with a nicer than expected size reduction with #49:

before:
```
237M  TheiaBlueprint-1.10.0.AppImage
187M  TheiaBlueprint-1.10.0.deb
```
after:
```
179M  TheiaBlueprint-1.10.0.AppImage
132M  TheiaBlueprint-1.10.0.deb
```
I'm curious if we'll see the same from what's built/signed on Jenkins. Where are these deployed?

**Comment by koegel** [comment] 2021-05-03 13:25
#49 was reverted due to build problems. We will take another brief look at this for the beta.

**Comment by marcdumais-work** [comment] 2021-05-03 19:12
Hi @koegel 

We've discussed it internally and, as we can tell, the `electron` runtime dependency in `@theia/electron` is needed until packaging-time, but not anymore at runtime. I think it can't be a `devDependency` because then it would be stripped when we do a production build, potentially making it impossible to package such a Theia app. 

So, Electron may need to remain a runtime dependency, but it could harmlessly be removed, after packaging (*). Maybe Electron Builder a pre-zip hook that could be used?

(*) For example we can play with the unzipped package:
```bash
$ cd theia-blueprint
$ yarn && yarn package:preview
# notice the electron libraries and binary (renamed to `theia-blueprint`), are there:
$ ls -al electron-app/dist/linux-unpacked/
# electron:
$ ls -al electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron/
$ electron libs + binary:
$ ls -al electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron/dist/
$ # It's almost 200MB, unzipped on disk:
$ du -hs  electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron
195M	electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron

# let's remove the electron folder, that should no longer be needed
$ cd electron-app/dist/linux-unpacked/
$ rm -rf electron-app/dist/linux-unpacked/resources/app/node_modules/@theia/electron/node_modules/electron
# Confirm the app still starts:
$ yarn start  
```

**Comment by koegel** [comment] 2021-05-03 19:20
Ok, thanks for the good input!

**Comment by marcdumais-work** [comment] 2021-08-13 17:27
Good news: with this recently merged PR (https://github.com/eclipse-theia/theia-blueprint/pull/131), we have achieved some package size reduction without sacrificing anything (just removing duplicated Electron biraries)



Linux Appimage previous size vs new:
![image](https://user-images.githubusercontent.com/25749063/129396496-36f9d064-2f47-40be-a535-0ebc765c8467.png)

The Mac package is now ~195MB and the Windows package is ~165MB.

**Comment by jfaltermeier** [comment] 2021-09-21 09:23
Since the electron binaries are only available once I think we may close this issue. If we find an area where we could improve disk size further, we may open a dedicated ticket for this.

At the moment the MacOS dmg is less than 200MB. When I copy it to the Application directory, it copies around 550MB. 
The electron framework + preinstalled extensions take around 350MB of thise 550MB. 
Those sizes are comparable to VS Code. 
![ksnip_20210921-111819](https://user-images.githubusercontent.com/5889696/134145770-470ae0a0-6e51-43b6-a99f-a5f20daae099.png)

**Closed by jfaltermeier** 2021-09-21 09:23 UTC
